name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7.15
  - ipykernel=4.8.2
  - numpy=1.16.5
  - matplotlib=2.2.5
  - scipy=1.2.1
  - h5py=2.10.0
  - IPython=5.8.0
  - decorator=4.4.2
